networks:
  experiment:

services:
  nsqlookupd:
    image: nsqio/nsq
    hostname: nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    expose:
      - 4160
      - 4161
    command: /nsqlookupd
    networks:
      - experiment

  nsqd:
    image: nsqio/nsq
    hostname: nsqd
    ports:
      - "4150:4150"
      - "4151:4151"
    command: /nsqd -broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    networks:
      - experiment
    expose:
      - 4150
      - 4151

  nsqadmin:
    image: nsqio/nsq
    hostname: nsqadmin
    ports:
      - "4170:4170"
      - "4171:4171"
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    networks:
      - experiment
    expose:
      - 4171

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    hostname: worker
    environment:
      - NSQ_ADDRESS=nsqd:4150
      - METRICS_PORT=2112
    ports:
      - "8081:8081"
      - "2112:2112"  # Expose metrics port
    networks:
      - experiment
    depends_on:
      - nsqd

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    hostname: backend
    environment:
      - NSQ_ADDRESS=nsqd:4150
      - METRICS_PORT=2113
    ports:
      - "8082:8082"
      - "2113:2113"  # Expose metrics port
    networks:
      - experiment
    depends_on:
      - nsqd

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - experiment
    depends_on:
      - worker

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - experiment
    depends_on:
      - prometheus

volumes:
  grafana-storage: {}
