global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:2112']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:2113']
